version: "3.8"

services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: app-php
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-php

    # nginx
    nginx:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-php

    # # db mysql
    # mysql:
    #     container_name: laravel-tdd-mysql
    #     image: mysql:5.7.22
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #     volumes:
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports:
    #         - "3388:3306"
    #     networks:
    #         - laravel-tdd

    # # queue
    # queue:
    #     container_name: laravel-tdd-queue
    #     image: especializati/laravel9-app
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         - redis
    #         - app
    #     networks:
    #         - laravel-tdd

    # # redis
    # redis:
    #     container_name: laravel-tdd-redis
    #     image: redis:latest
    #     networks:
    #         - laravel-tdd

networks:
    app-php:
        driver: bridge